// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/service/transaction_service.go

// Package service is a generated GoMock package.
package service

import (
	model "bank-statement-viewer-backend/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTransactionService is a mock of TransactionService interface.
type MockTransactionService struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionServiceMockRecorder
}

// MockTransactionServiceMockRecorder is the mock recorder for MockTransactionService.
type MockTransactionServiceMockRecorder struct {
	mock *MockTransactionService
}

// NewMockTransactionService creates a new mock instance.
func NewMockTransactionService(ctrl *gomock.Controller) *MockTransactionService {
	mock := &MockTransactionService{ctrl: ctrl}
	mock.recorder = &MockTransactionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionService) EXPECT() *MockTransactionServiceMockRecorder {
	return m.recorder
}

// CalculateBalance mocks base method.
func (m *MockTransactionService) CalculateBalance() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateBalance")
	ret0, _ := ret[0].(int64)
	return ret0
}

// CalculateBalance indicates an expected call of CalculateBalance.
func (mr *MockTransactionServiceMockRecorder) CalculateBalance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateBalance", reflect.TypeOf((*MockTransactionService)(nil).CalculateBalance))
}

// GetAll mocks base method.
func (m *MockTransactionService) GetAll() []model.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]model.Transaction)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockTransactionServiceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockTransactionService)(nil).GetAll))
}

// GetIssues mocks base method.
func (m *MockTransactionService) GetIssues() []model.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssues")
	ret0, _ := ret[0].([]model.Transaction)
	return ret0
}

// GetIssues indicates an expected call of GetIssues.
func (mr *MockTransactionServiceMockRecorder) GetIssues() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssues", reflect.TypeOf((*MockTransactionService)(nil).GetIssues))
}

// SaveTransactions mocks base method.
func (m *MockTransactionService) SaveTransactions(arg0 []model.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTransactions", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTransactions indicates an expected call of SaveTransactions.
func (mr *MockTransactionServiceMockRecorder) SaveTransactions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTransactions", reflect.TypeOf((*MockTransactionService)(nil).SaveTransactions), arg0)
}
