// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/repository/transaction_repo.go

// Package repository is a generated GoMock package.
package repository

import (
	model "bank-statement-viewer-backend/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// AppendAll mocks base method.
func (m *MockTransactionRepository) AppendAll(arg0 []model.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendAll", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendAll indicates an expected call of AppendAll.
func (mr *MockTransactionRepositoryMockRecorder) AppendAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendAll", reflect.TypeOf((*MockTransactionRepository)(nil).AppendAll), arg0)
}

// Clear mocks base method.
func (m *MockTransactionRepository) Clear() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear")
}

// Clear indicates an expected call of Clear.
func (mr *MockTransactionRepositoryMockRecorder) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockTransactionRepository)(nil).Clear))
}

// GetAll mocks base method.
func (m *MockTransactionRepository) GetAll() []model.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]model.Transaction)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockTransactionRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockTransactionRepository)(nil).GetAll))
}

// SaveAll mocks base method.
func (m *MockTransactionRepository) SaveAll(arg0 []model.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAll", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAll indicates an expected call of SaveAll.
func (mr *MockTransactionRepositoryMockRecorder) SaveAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAll", reflect.TypeOf((*MockTransactionRepository)(nil).SaveAll), arg0)
}
